title: Md Alomgeer Hussein
url: "https://mdalomgeer.github.io"
baseurl:

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Md Alomgeer Hussein"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Publications"
   link: "resume.pdf"
 - name: "Projects"
   link: "contact"
 - name: "Teachings"
   link: "resume.pdf"
 - name: "Groups"
   link: "contact"
 - name: "Misc"
   link: "contact"
   
