title: Hussein
url: "https://mdalomgeer.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/mdalomgeer"

footer_links:
  - name: "Email"
    url: "mailto:mdalomh1@umbc.edu"
  - name: "Scholar"
    url: "https://scholar.google.com/citations?user=bftKphkAAAAJ&hl=en&authuser=2"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/alomgeer/"

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  - name: "Publications"
    link: "/publications/"
  - name: "Projects"
    link: "/projects/"
  - name: "Teaching"
    link: "/teaching/"
  - name: "Groups"
    link: "/groups/"
  - name: "Misc"
    link: "/misc/"
