title: Hussein
url: "https://mdalomgeer.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/mdalomgeer"
footer_text: "Page design by Md Alomgeer Hussein"

footer_links:
  - name: "Email"
    url: "mailto:your-email@example.com"
  - name: "Scholar"
    url: "https://scholar.google.com/citations?user=YOUR_ID"
  - name: "Source"
    url: "https://github.com/mdalomgeer/mdalomgeer.github.io"

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  - name: "Publications"
    link: "/publications/"
  - name: "Projects"
    link: "/projects/"
  - name: "Teaching"
    link: "/teaching/"
  - name: "Groups"
    link: "/groups/"
  - name: "Misc"
    link: "/misc/"
  - name: "CV"
    link: "/Resume-Alomgeer.pdf"
